//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace biopot.Resources.Strings {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("biopot.Resources.Strings.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply.
        /// </summary>
        public static string Apply {
            get {
                return ResourceManager.GetString("Apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please be careful when changing these settings!.
        /// </summary>
        public static string BeCarefulWhenChangingSettings {
            get {
                return ResourceManager.GetString("BeCarefulWhenChangingSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To connect the device to phone, turn on bluetooth! Please turn on bluetooth.
        /// </summary>
        public static string BluetoothNotEnabledAlert {
            get {
                return ResourceManager.GetString("BluetoothNotEnabledAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection Failed.
        /// </summary>
        public static string ConnectionFailed {
            get {
                return ResourceManager.GetString("ConnectionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connections.
        /// </summary>
        public static string Connections {
            get {
                return ResourceManager.GetString("Connections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BioPot.
        /// </summary>
        public static string DefaultFileName {
            get {
                return ResourceManager.GetString("DefaultFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Biopot data files.
        /// </summary>
        public static string DefaultFolderName {
            get {
                return ResourceManager.GetString("DefaultFolderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accelerometer Channels.
        /// </summary>
        public static string DeviceAccelerometerChannelsCount {
            get {
                return ResourceManager.GetString("DeviceAccelerometerChannelsCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accelerometer.
        /// </summary>
        public static string DeviceConfigurationAccelerometer {
            get {
                return ResourceManager.GetString("DeviceConfigurationAccelerometer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bio-impedance.
        /// </summary>
        public static string DeviceConfigurationBoImpedance {
            get {
                return ResourceManager.GetString("DeviceConfigurationBoImpedance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bio-impendance ({0} ch.).
        /// </summary>
        public static string DeviceConfigurationBoImpedanceWithChannels {
            get {
                return ResourceManager.GetString("DeviceConfigurationBoImpedanceWithChannels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} channels.
        /// </summary>
        public static string DeviceConfigurationChannelsNum {
            get {
                return ResourceManager.GetString("DeviceConfigurationChannelsNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EEG/EMG Channels.
        /// </summary>
        public static string DeviceEegChannelsCount {
            get {
                return ResourceManager.GetString("DeviceEegChannelsCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bio Impedance Channels.
        /// </summary>
        public static string DeviceImpedanceChannelsCount {
            get {
                return ResourceManager.GetString("DeviceImpedanceChannelsCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done.
        /// </summary>
        public static string Done {
            get {
                return ResourceManager.GetString("Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        public static string EmpID {
            get {
                return ResourceManager.GetString("EmpID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, we couldn’t find any Bluetooth 
        ///devices.
        /// </summary>
        public static string EmptyConnections {
            get {
                return ResourceManager.GetString("EmptyConnections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refer to manual for details.
        /// </summary>
        public static string EraseModeNotificationSubtitle {
            get {
                return ResourceManager.GetString("EraseModeNotificationSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cleaning buffer memory, please wait.
        /// </summary>
        public static string EraseModeNotificationTitle {
            get {
                return ResourceManager.GetString("EraseModeNotificationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to connect to the BioPot device (error code {0}). Please click the logo on the top left or restart the app, and try to connect again from the welcome screen..
        /// </summary>
        public static string ErrorConnectionLostMessage {
            get {
                return ResourceManager.GetString("ErrorConnectionLostMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection to BioBot was lost.
        /// </summary>
        public static string ErrorConnectionLostTitle {
            get {
                return ResourceManager.GetString("ErrorConnectionLostTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The saving target is not accessible or is giving errors (error code {0}). Please restart the app and select a different saving target from the &quot;Session Details&quot; tab in the welcome screen..
        /// </summary>
        public static string ErrorDataSaveMessage {
            get {
                return ResourceManager.GetString("ErrorDataSaveMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to save data to memory.
        /// </summary>
        public static string ErrorDataSaveTitle {
            get {
                return ResourceManager.GetString("ErrorDataSaveTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to retrieve signals from the BioPot device (error code {0}). Please try to reset the device and then restart the app..
        /// </summary>
        public static string ErrorSignalRetrieveMessage {
            get {
                return ResourceManager.GetString("ErrorSignalRetrieveMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not retrieve signals from the BioPot.
        /// </summary>
        public static string ErrorSignalRetrieveTitle {
            get {
                return ResourceManager.GetString("ErrorSignalRetrieveTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Example.
        /// </summary>
        public static string Example {
            get {
                return ResourceManager.GetString("Example", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Female.
        /// </summary>
        public static string Female {
            get {
                return ResourceManager.GetString("Female", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Name.
        /// </summary>
        public static string FileName {
            get {
                return ResourceManager.GetString("FileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder Name.
        /// </summary>
        public static string FolderName {
            get {
                return ResourceManager.GetString("FolderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder will be saved under root in saving target.
        /// </summary>
        public static string FolderWillBe {
            get {
                return ResourceManager.GetString("FolderWillBe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gender.
        /// </summary>
        public static string Gender {
            get {
                return ResourceManager.GetString("Gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        public static string ID {
            get {
                return ResourceManager.GetString("ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal Memory.
        /// </summary>
        public static string InternalMemory {
            get {
                return ResourceManager.GetString("InternalMemory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal SD Card.
        /// </summary>
        public static string InternalSDCard {
            get {
                return ResourceManager.GetString("InternalSDCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locating Connections....
        /// </summary>
        public static string LocatingConnections {
            get {
                return ResourceManager.GetString("LocatingConnections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to connect to the BioPot device. Please click the logo on the top left or restart the app, and try to connect again from the welcome screen..
        /// </summary>
        public static string LostConnectionErrorText {
            get {
                return ResourceManager.GetString("LostConnectionErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection to BioBot was lost.
        /// </summary>
        public static string LostConnectionTitle {
            get {
                return ResourceManager.GetString("LostConnectionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Male.
        /// </summary>
        public static string Male {
            get {
                return ResourceManager.GetString("Male", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must enable the memory permission.
        /// </summary>
        public static string NeedEnablePermissionMemory {
            get {
                return ResourceManager.GetString("NeedEnablePermissionMemory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No channels selected.
        /// </summary>
        public static string NoChannelsSelected {
            get {
                return ResourceManager.GetString("NoChannelsSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not connected.
        /// </summary>
        public static string NoConnectedTitle {
            get {
                return ResourceManager.GetString("NoConnectedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to retrieve signals from the BioPot device. Please try to reset the device and then restart the app..
        /// </summary>
        public static string NotRetrieveSignalBody {
            get {
                return ResourceManager.GetString("NotRetrieveSignalBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not retrieve signals from the BioPot.
        /// </summary>
        public static string NotRetrieveSignalTitle {
            get {
                return ResourceManager.GetString("NotRetrieveSignalTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        public static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other Details.
        /// </summary>
        public static string OtherDetails {
            get {
                return ResourceManager.GetString("OtherDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patient Details.
        /// </summary>
        public static string PatientDetails {
            get {
                return ResourceManager.GetString("PatientDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patient Code.
        /// </summary>
        public static string PatientDetailsPatientCodeScanned {
            get {
                return ResourceManager.GetString("PatientDetailsPatientCodeScanned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patient Code (scan or enter).
        /// </summary>
        public static string PatientDetailsPatientCodeScanOrEnter {
            get {
                return ResourceManager.GetString("PatientDetailsPatientCodeScanOrEnter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scanning failed, please try again.
        /// </summary>
        public static string PatientDetailsScanFailed {
            get {
                return ResourceManager.GetString("PatientDetailsScanFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Place patient barcode inside the blue frame.
        /// </summary>
        public static string PatientDetailsScanHelpMessage {
            get {
                return ResourceManager.GetString("PatientDetailsScanHelpMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scanning barcode....
        /// </summary>
        public static string PatientDetailsScanningBarcode {
            get {
                return ResourceManager.GetString("PatientDetailsScanningBarcode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        public static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter all required fields.
        /// </summary>
        public static string PleaseEnterAllFields {
            get {
                return ResourceManager.GetString("PleaseEnterAllFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Try again.
        /// </summary>
        public static string Retry {
            get {
                return ResourceManager.GetString("Retry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role.
        /// </summary>
        public static string Role {
            get {
                return ResourceManager.GetString("Role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving Target.
        /// </summary>
        public static string SavingTarget {
            get {
                return ResourceManager.GetString("SavingTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a BioPot to connect:.
        /// </summary>
        public static string SelectBioPot {
            get {
                return ResourceManager.GetString("SelectBioPot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sequential Number.
        /// </summary>
        public static string SequentialNumber {
            get {
                return ResourceManager.GetString("SequentialNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Session Details.
        /// </summary>
        public static string SessionDetails {
            get {
                return ResourceManager.GetString("SessionDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share via.
        /// </summary>
        public static string ShareVia {
            get {
                return ResourceManager.GetString("ShareVia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong. Please, try again.
        /// </summary>
        public static string SomethingWentWrong {
            get {
                return ResourceManager.GetString("SomethingWentWrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        public static string Start {
            get {
                return ResourceManager.GetString("Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait until synch is completed before you can proceed (estimated 10-30 seconds).
        /// </summary>
        public static string SyncModeActiveMessage {
            get {
                return ResourceManager.GetString("SyncModeActiveMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hardware Synch in Progress.
        /// </summary>
        public static string SyncModeActiveTitle {
            get {
                return ResourceManager.GetString("SyncModeActiveTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Synch completed, please remove synch cable..
        /// </summary>
        public static string SyncModeFinishedMessage {
            get {
                return ResourceManager.GetString("SyncModeFinishedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hardware Synch Completed.
        /// </summary>
        public static string SyncModeFinishedTitle {
            get {
                return ResourceManager.GetString("SyncModeFinishedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}°C.
        /// </summary>
        public static string TemperatureCelsiusFormat {
            get {
                return ResourceManager.GetString("TemperatureCelsiusFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time.
        /// </summary>
        public static string Time {
            get {
                return ResourceManager.GetString("Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additional Settings.
        /// </summary>
        public static string ToolbarAdditionalSettings {
            get {
                return ResourceManager.GetString("ToolbarAdditionalSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patient/Session/User Setup.
        /// </summary>
        public static string ToolbarAdvancedSetup {
            get {
                return ResourceManager.GetString("ToolbarAdvancedSetup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} SPS.
        /// </summary>
        public static string ToolbarSPS {
            get {
                return ResourceManager.GetString("ToolbarSPS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To connect the device to phone, turn on bluetooth!.
        /// </summary>
        public static string TurnedOffBlueToothAlertBody {
            get {
                return ResourceManager.GetString("TurnedOffBlueToothAlertBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bluetooth is off!.
        /// </summary>
        public static string TurnedOffBlueToothAlertTitle {
            get {
                return ResourceManager.GetString("TurnedOffBlueToothAlertTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to save data to memory.
        /// </summary>
        public static string UnableSaveData {
            get {
                return ResourceManager.GetString("UnableSaveData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The saving target is not accessible or is giving errors. Please restart the app and select a different saving target from the &quot;Session Details&quot; tab in the welcome screen..
        /// </summary>
        public static string UnableSaveDataDescription {
            get {
                return ResourceManager.GetString("UnableSaveDataDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USB OTG Cable.
        /// </summary>
        public static string USBCable {
            get {
                return ResourceManager.GetString("USBCable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Details.
        /// </summary>
        public static string UserDetails {
            get {
                return ResourceManager.GetString("UserDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wireless Stick.
        /// </summary>
        public static string WirelessStick {
            get {
                return ResourceManager.GetString("WirelessStick", resourceCulture);
            }
        }
    }
}
